---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-argocd
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  stripPrefix:
    prefixes:
      - /argocd
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "PathPrefix(`/argocd`)"
      middlewares:
        - name: strip-prefix-argocd@kubernetescrd
      services:
        - name: argocd-server
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-traefik
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  stripPrefix:
    prefixes:
      - /traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "PathPrefix(`/traefik`)"
      middlewares:
        - name: strip-prefix-traefik@kubernetescrd
      services:
        - name: api@internal
          kind: TraefikService
