traefik:
  ingressRoute:
    dashboard:
      enabled: false
  podSecurityPolicy:
    enabled: false
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  ports:
    web:
      redirectTo:
        port: websecure
  providers:
    kubernetesIngress:
      ingressClass: traefik
