traefik:
  ingressRoute:
    dashboard:
      enabled: false
  podSecurityPolicy:
    enabled: false
  ports:
    websecure:
      redirectTo:
        port: web # TODO: disabled HTTPS for MVP
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      allowExternalNameServices: true
    kubernetesIngress:
      ingressClass: traefik
