traefik:
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: PathPrefix(`/traefik`)
      entrypoints:
        - websecure
      middlewares:
        - "strip-prefix-traefik"
  podSecurityPolicy:
    enabled: false
  ports:
    web:
      redirectTo:
        port: websecure
  providers:
    kubernetesIngress:
      ingressClass: traefik
    kubernetesCRD:
      allowCrossNamespace: true
