traefik:
  ingressRoute:
    dashboard:
      enabled: false
  podSecurityPolicy:
    enabled: false
  ports:
    web:
      redirectTo:
        port: websecure
  providers:
    kubernetesIngress:
      ingressClass: traefik
    kubernetesCRD:
      allowCrossNamespace: true
