apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - https://raw.githubusercontent.com/Azure/AKS-Edge/main/samples/others/metrics-server.yaml
