apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
