argocd-apps:
  projects:
    - name: system
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'

  applications:
    - name: bespoke
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: default
      destination:
        name: in-cluster
        namespace: argocd
      source:
        repoURL: https://github.com/frealmyr/containers-assignment-apps
        targetRevision: main
        path: .
      syncPolicy:
        automated:
          prune: true
          selfHeal: false

    - name: traefik
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: system
      destination:
        name: in-cluster
        namespace: traefik
      source:
        repoURL: https://github.com/frealmyr/containers-assignment
        targetRevision: main
        path: gitops/system/traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true

    - name: metrics-server
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: system
      destination:
        name: in-cluster
        namespace: kube-system
      source:
        repoURL: https://github.com/frealmyr/containers-assignment
        targetRevision: main
        path: gitops/system/metrics-server
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
      additionalAnnotations:
        argocd.argoproj.io/sync-wave: "-1"
